# Generated by Django 5.1.1 on 2025-07-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variiations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
