# Generated by Django 5.1.1 on 2025-07-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitems_variiations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='variiations',
            new_name='variations',
        ),
    ]
